from settings import settings


SYSTEM_PROMPT = settings.SYSTEM_PROMPT
SUMMARY_PROMPT = settings.SUMMARY_PROMPT
FACT_JUDGE_PROMPT = settings.FACT_JUDGE_PROMPT

SUMMARY_EVERY_N_MESSAGES = settings.SUMMARY_EVERY_N_MESSAGES
SUMMARY_MAX_FACTS = settings.SUMMARY_MAX_FACTS
MEMORY_SEARCH_LIMIT = settings.MEMORY_SEARCH_LIMIT
FACT_SIMILARITY_LOW = settings.FACT_SIMILARITY_LOW
FACT_SIMILARITY_HIGH = settings.FACT_SIMILARITY_HIGH
FACT_JUDGE_MODEL = settings.FACT_JUDGE_MODEL
BASE_MODEL = settings.BASE_MODEL
BASE_MODEL_TEMPERATURE = settings.BASE_MODEL_TEMPERATURE
BASE_MODEL_TOP_K = settings.BASE_MODEL_TOP_K
BASE_MODEL_TOP_P = settings.BASE_MODEL_TOP_P
LLM_BASE_URL = settings.LLM_BASE_URL
LLM_API_KEY = settings.LLM_API_KEY
QDRANT_HOST = settings.QDRANT_HOST
QDRANT_PORT = settings.QDRANT_PORT
FACT_JUDGE_TIMEOUT_SEC = settings.FACT_JUDGE_TIMEOUT_SEC
MEMORY_PIPELINE_LOGS_ENABLED = settings.MEMORY_PIPELINE_LOGS_ENABLED
ARCHIVIST_TEMPERATURE = settings.ARCHIVIST_TEMPERATURE
FACT_JUDGE_TEMPERATURE = settings.FACT_JUDGE_TEMPERATURE

MEMORY_MIN_VECTOR_SCORE = settings.MEMORY_MIN_VECTOR_SCORE

MEMORY_RERANK_MODEL = settings.MEMORY_RERANK_MODEL
MEMORY_RERANK_TEMPERATURE = settings.MEMORY_RERANK_TEMPERATURE
MEMORY_RERANK_WEIGHT = settings.MEMORY_RERANK_WEIGHT
MEMORY_VECTOR_WEIGHT = settings.MEMORY_VECTOR_WEIGHT

MEMORY_RETRIEVAL_TOP_K = settings.MEMORY_RETRIEVAL_TOP_K
MEMORY_RERANK_TOP_N = settings.MEMORY_RERANK_TOP_N
MEMORY_CONTEXT_FACTS_LIMIT = settings.MEMORY_CONTEXT_FACTS_LIMIT
MEMORY_RERANK_ENABLED = settings.MEMORY_RERANK_ENABLED